### PR TITLE
Change file extension of Fortran source files to .f90

### PR DESCRIPTION
**Pull request by MakisH**
Did you ever wonder "what is really Fortran 2003 in the code we have here"? Well, nothing.

Did you ever wonder "why do I need to specify the standard version as a file extension, while in C++ I don't"? Well, that's actually a common misunderstanding. The file extensions `.f90`, `.f95`, `.f03`, ... all are the same for the compiler. Even further, not all compilers recognize all extensions.

As the [Fortran Wiki](https://fortranwiki.org/fortran/show/File+extensions) states (and as @ivan-pi raised), the only difference that matters is `.f` (fixed format) or `.f90` (free format). It is just that `.f90` is an unfortunate name.

It seems like the best practice here is to always use `.f90`, even if one uses newer features. And since we are not even using newer features, let's just stop confusing people.

FYI, the modules are part of Fortran 90 already.

@uekerman any objections to this change? This also goes into the architecture picture, that's why I am doing this now.

### CODE REVIEW

**Comment by ivan-pi** [comment]
I've got a chart of file extensions supported by each compiler here: https://github.com/fortran-lang/fpm/issues/250#issue-748665600

`.f` for fixed-format, and `.f90` for free-format, are the ones which are supported by default by all the compilers today, hence they create the least friction. It is really just a convention like the use of `.cc`/`.cpp`/`.cxx` for C++. Unfortunately, `.f90` gives the false impression that Fortran 90 is used, but it only affects the way Fortran is parsed. 

In principle you could write Fortran on parchment in gothic characters, and have it delivered to a compiler (or "processor" in Fortran jargon) by a carrier pigeon. :)

**Comment by uekerman** [comment]
> @uekerman any objections to this change? This also goes into the architecture picture, that's why I am doing this now.

Not from my side. IIRC this was originally proposed by @haraldkl. Any idea or concern, Harald?

**Comment by haraldkl** [comment]
No, all our files with free format are named `.f90`, see also [here](https://github.com/apes-suite/aotus/tree/branch/default/source), for example. Also the [PreCICE related files](https://github.com/apes-suite/tem-source/tree/8c57d7d7bc524fd4ca65708e8873e2162b9994cc/external/precice) in our code are named `.f90`. I don't think it was my idea to use f03. I know that some compilers automatically selected the standard according to the file extension, but it is better to provide that explicitly as a command line argument to the compiler instead, because you can't rely on compilers doing it anyway. I agree with @MakisH that it is best practice to use `.f90` for free-form and `.f` for fixed-form.

**Comment by MakisH** [comment]
Just out of curiosity, some history research:

- The files first appear in the preCICE Git repository in May 2013 as [`src/precice/adapters/f2003/PreCICE_solver_if_module.f90`](https://github.com/precice/precice/commit/2057e5cde4f97d746c610809195ec525240914e3#diff-5a4b9a11d8a7937acc8ca1e1ed7fd9a49498c602bbd3f56327dfb91623365b6c)
- The same day, @haraldkl renamed `f2003/PreCICE_solver_if_module.f90` to `f2003/SolverInterfaceF2003.f90` (https://github.com/precice/precice/commit/9e899d985ea6ca8afd20d64d7956540a5d363768)
- Preparing for preCICE v2, these files were moved to this repository, with the same name.
- In preCICE v2, I renamed the file `SolverInterfaceF2003.f90` to `precice.f03` (https://github.com/precice/fortran-module/commit/4be41c29424fa7e1e6be035b0cc87bb1d29f9f41). At the time, I was convinced by the name that these bindings had something to do with Fortran 2003 and the discussion concluded in keeping that in the name.

So, I will happily take the responsibility for the `.f03`, since at least the renaming commit was mine. I still wonder why the "Fortran 2003" in the name, but I have no idea how to distinguish a Fortran 2003 from a Fortran 90 code.

Thank you all for clarifying, let's all keep learning!

**Comment by haraldkl** [comment]
The C-Interface functionalities were introduced in F2003. It's a little bit akin to how the MPI modules offer now an `mpi_f08` module because it makes use of Features that were introduced in F2008. In any case, basically all modern Fortran compilers [should support](https://fortranwiki.org/fortran/show/Fortran+2003+status) (see last block of rows) the C-Interfacing capabilities from F2003 by now, so there isn't really a reason to refer to it here anyway.

**Comment by MakisH** [comment]
I see, I had the impression that interoperability with C was already there since Fortran 90. Thank you for clarifying!

**Pull request merged**
